version: '3.9'
networks:
  basic:
services:
  front:
    # build:
    #   context: ./
    #   dockerfile: Dockerfile
    #   target: front
    container_name: greaterwms_front_lite
    image: greaterwms/greaterwms:front
    restart: always
    privileged: true
    ports:
      - '9000:9000'
    volumes:
      - ./templates:/GreaterWMS/templates:rw
      - ./web_start.sh:/GreaterWMS/templates/web_start.sh
    networks:
      - basic
